executor: slurm

jobs: 999
local-cores: 1
max-status-checks-per-second: 1
max-jobs-per-second: 1
restart-times: 2

default-resources:
    runtime: 120
    mem_mb: 4000
    slurm_partition: "core"

set-resources:
  post_process_tnscope_info_fields_wgs:
    runtime: 60
    mem_mb: 5000 * attempt
  post_process_tnscope_info_fields_tga:
    runtime: 60
    mem_mb: 5000 * attempt
  tnscope_sort:
    runtime: 60
    mem_mb: 8000 * attempt
  merge_tnscope_to_mnvs:
    runtime: 60
    mem_mb: 8000 * attempt
  cnvpytor_tumor_only_wgs:
    runtime: 600
    mem_mb: 60000 * attempt
  igh_dux4_detection_tumor_only_wgs:
    runtime: 120
    mem_mb: 5000 * attempt
  igh_dux4_detection_tumor_normal_wgs:
    runtime: 120
    mem_mb: 5000 * attempt
  tiddit_sv_tumor_only_wgs:
    runtime: 600
    mem_mb: 30000  * attempt
  tiddit_sv_tumor_normal_wgs:
    runtime: 600
    mem_mb: 40000 * attempt
  ascat_tumor_normal_wgs:
    runtime: 600
    mem_mb: 60000 * attempt
  delly_cnv_tumor_only:
    runtime: 340
    mem_mb: 20000 * attempt
  delly_cnv_tumor_normal:
    runtime: 340
    mem_mb: 20000 * attempt
  delly_cnv_tumor_only_wgs:
    runtime: 600
    mem_mb: 30000 * attempt
  delly_cnv_tumor_normal_wgs:
    runtime: 600
    mem_mb: 30000 * attempt
  delly_sv_tumor_only_wgs:
    runtime: 600
    mem_mb: 30000 * attempt
  delly_sv_tumor_normal_wgs:
    runtime: 600
    mem_mb: 30000 * attempt
  manta_tumor_only_wgs:
    runtime: 600
    mem_mb: 10000 * attempt
  manta_tumor_normal_wgs:
    runtime: 600
    mem_mb: 15000 * attempt
  delly_sv_tumor_only_tga:
    runtime: 340
    mem_mb: 10000 * attempt
  delly_sv_tumor_normal_tga:
    runtime: 340
    mem_mb: 10000 * attempt
  manta_tumor_only_tga:
    runtime: 340
    mem_mb: 10000 * attempt
  manta_tumor_normal_tga:
    runtime: 340
    mem_mb: 15000 * attempt
  bcftools_quality_filter_svdb:
    runtime: 60
    mem_mb: 10000 * attempt
  svdb_merge_tumor_only:
    runtime: 60
    mem_mb: 10000 * attempt
  svdb_merge_tumor_normal:
    runtime: 60
    mem_mb: 10000 * attempt
  bcftools_process_SV_CNV:
    runtime: 60
    mem_mb: 10000 * attempt
  bcftools_sort_cnvkitCNV_research:
    runtime: 60
    mem_mb: 10000 * attempt
  cnvkit_call_CNV_research:
    mem_mb: 5000 * attempt
    runtime: 360
  purecn_call_CNV_research:
    mem_mb: 20000 * attempt
    runtime: 360
  bedtools_pad_bedfile:
    mem_mb: 1000 * attempt
    runtime: 20
  vardict_sort:
    mem_mb: 15000 * attempt
    runtime: 30
  gatk_update_vcf_sequence_dictionary:
    runtime: 600
    mem_mb: 10000 * attempt
  cnvkit_segment_CNV_research:
    runtime: 360
    mem_mb: 5000 * attempt
  bcftools_merge_germlineSNV_research:
    runtime: 280
    mem_mb: 10000 * attempt
  vardict_tumor_normal:
    runtime: 280
    mem_mb: 40000 * attempt
  sentieon_tnscope_tga_tumor_normal:
    mem_mb: 25000 * attempt
    runtime: 280
  post_process_vardict:
    runtime: 280
    mem_mb: 5000 * attempt
  vardict_tumor_only:
    runtime: 280
    mem_mb: 20000 * attempt
  sentieon_tnscope_tga_tumor_only:
    runtime: 280
  bcftools_quality_filter_TNscope_umi_tumor_only:
    runtime: 100
    mem_mb: 10000 * attempt
  bcftools_quality_filter_TNscope_umi_tumor_normal:
    runtime: 100
    mem_mb: 10000 * attempt
  bcftools_quality_filter_vardict_tumor_normal:
    runtime: 100
    mem_mb: 10000 * attempt
  bcftools_quality_filter_tnscope_tumor_normal_tga:
    runtime: 100
    mem_mb: 10000 * attempt
  bcftools_quality_filter_vardict_tumor_only:
    runtime: 100
    mem_mb: 10000 * attempt
  bcftools_quality_filter_tnscope_tumor_only_tga:
    runtime: 100
    mem_mb: 10000 * attempt
  bcftools_quality_filter_tnscope_tumor_normal_wgs:
    runtime: 100
    mem_mb: 10000 * attempt
  bcftools_quality_filter_tnscope_tumor_only_wgs:
    runtime: 100
    mem_mb: 10000 * attempt
  sentieon_tnscope_wgs_tumor_normal:
    runtime: 1440
    mem_mb: 40000 * attempt
  sentieon_tnscope_wgs_tumor_only:
    runtime: 1440
    mem_mb: 45000 * attempt
  merge_snv_vcfs:
    runtime: 120
    mem_mb: 20000 * attempt
  bcftools_normalise_vcfs:
    runtime: 120
    mem_mb: 4000 * attempt
  manta_germline_wgs:
    runtime: 1440
    mem_mb: 60000 * attempt
  sentieon_DNAscope_wgs:
    runtime: 1440
    mem_mb: 50000 * attempt
  manta_germline_tga:
    runtime: 300
    mem_mb: 40000 * attempt
  sentieon_DNAscope_tga:
    runtime: 1440
    mem_mb: 25000 * attempt
  finalize_gens_outputfiles:
    runtime: 60
    mem_mb: 2000 * attempt
  gens_preprocess_tga:
    runtime: 60
    mem_mb: 10000 * attempt
  sentieon_DNAscope_gnomad_tga:
    runtime: 1440
    mem_mb: 25000 * attempt
  gens_preprocess_wgs:
    runtime: 60
    mem_mb: 10000 * attempt
  gatk_denoise_read_counts:
    runtime: 600
    mem_mb: 70000 * attempt
  sentieon_DNAscope_gnomad:
    runtime: 1440
    mem_mb: 60000 * attempt
  gatk_collectreadcounts:
    runtime: 350
    mem_mb: 40000 * attempt
  bedtools_sort_and_merge:
    runtime: 20
    mem_mb: 400 * attempt
  extend_short_bedregions:
    runtime: 20
    mem_mb: 400 * attempt
  create_coverage:
    runtime: 360
    mem_mb: 30000 * attempt
  create_target:
    runtime: 360
    mem_mb: 5000 * attempt
  sentieon_align_sort_umireads_umi:
    runtime: 1440
    mem_mb: 26000 * attempt
  sentieon_tnscope_umi_tn:
    runtime: 280
    mem_mb: 10000 * attempt
  sentieon_tnscope_umi:
    runtime: 280
    mem_mb: 10000 * attempt
  bam_compress_normal_umi:
    runtime: 280
    mem_mb: 16000 * attempt
  bam_compress_tumor_umi:
    runtime: 280
    mem_mb: 16000 * attempt
  sentieon_consensusfilter_umi:
    runtime: 280
    mem_mb: 16000 * attempt
  sentieon_bwa_umiconsensus:
    runtime: 480
    mem_mb: 30000 * attempt
  sentieon_consensuscall_umi:
    runtime: 360
    mem_mb: 16000 * attempt
  samtools_view_calculatemeanfamilydepth_umi:
    runtime: 280
    mem_mb: 16000 * attempt
  picard_collecthsmetrics_umi:
    runtime: 280
    mem_mb: 16000 * attempt
  picard_umiaware:
    runtime: 280
    mem_mb: 16000 * attempt
  modify_tnscope_infofield_umi:
    runtime: 60
    mem_mb: 10000 * attempt
  bcftools_query_generatebackgroundaf_umitable:
    runtime: 60
    mem_mb: 10000 * attempt
  merge_cnv_pdf_reports:
    runtime: 60
    mem_mb: 5000 * attempt
  image_to_pdf:
    runtime: 60
    mem_mb: 5000 * attempt
  msi_to_pdf:
    runtime: 60
    mem_mb: 5000 * attempt
  txt_to_pdf:
    runtime: 60
    mem_mb: 5000 * attempt
  csv_to_pdf:
    runtime: 60
    mem_mb: 5000 * attempt
  somalier_relate:
    runtime: 60
    mem_mb: 5000 * attempt
  somalier_extract_tumor:
    runtime: 60
    mem_mb: 5000 * attempt
  somalier_extract_normal:
    runtime: 60
    mem_mb: 5000 * attempt
  sex_prediction_tga_tumor_only:
    runtime: 60
    mem_mb: 5000 * attempt
  sex_prediction_tga_tumor_normal:
    runtime: 60
    mem_mb: 5000 * attempt
  sex_prediction_wgs_tumor_only:
    runtime: 60
    mem_mb: 5000 * attempt
  sex_prediction_wgs_tumor_normal:
    runtime: 60
    mem_mb: 5000 * attempt
  sentieon_plot_qc_metrics_tga:
    runtime: 30
    mem_mb: 2000 * attempt
  sentieon_plot_qc_metrics_wgs:
    runtime: 30
    mem_mb: 5000 * attempt
  sentieon_qc_metrics_tga:
    runtime: 280
    mem_mb: 30000 * attempt
  sentieon_qc_metric_wgs:
    runtime: 280
    mem_mb: 25000 * attempt
  sentieon_wgs_metrics:
    runtime: 280
    mem_mb: 30000 * attempt
  picard_CollectWgsMetrics:
    runtime: 900
    mem_mb: 30000 * attempt
  samtools_qc_umi_collapsed:
    runtime: 280
    mem_mb: 8000 * attempt
  samtools_qc_tga:
    runtime: 280
    mem_mb: 8000 * attempt
  samtools_qc_wgs:
    runtime: 280
    mem_mb: 8000 * attempt
  sambamba_exon_depth:
    runtime: 150
    mem_mb: 12000 * attempt
  sambamba_panel_depth:
    runtime: 150
    mem_mb: 8000 * attempt
  cnv_report:
    runtime: 20
    mem_mb: 100 * attempt
  collect_custom_qc_metrics:
    runtime: 20
    mem_mb: 1000 * attempt
  picard_CollectHsMetrics_WGS:
    runtime: 360
    mem_mb: 25000 * attempt
  picard_CollectAlignmentSummaryMetrics:
    runtime: 900
    mem_mb: 30000 * attempt
  picard_CollectHsMetrics:
    runtime: 360
    mem_mb: 25000 * attempt
  multiqc:
    runtime: 60
    mem_mb: 5000 * attempt
  mosdepth_coverage:
    runtime: 280
    mem_mb: 5000 * attempt
  gatk_create_readcount_pon:
    runtime: 3600
    mem_mb: 170000 * attempt
  create_reference:
    runtime: 120
    mem_mb: 15000 * attempt
  dragen_align_call_tumor_only:
    runtime: 1200
    mem_mb: 120000 * attempt
  concatenate_fastqs:
    runtime: 60
    mem_mb: 5000 * attempt
  vcfheader_rename_germline:
    runtime: 120
    mem_mb: 1000 * attempt
  vcf2cytosure_convert_tumor_normal:
    runtime: 120
    mem_mb: 10000 * attempt
  vcf2cytosure_convert_tumor_only:
    runtime: 120
    mem_mb: 10000 * attempt
  vcf2cytosure_convert:
    runtime: 120
    mem_mb: 10000 * attempt
  bcftools_filter_sv_research:
    runtime: 120
    mem_mb: 10000 * attempt
  bcftools_filter_sv_clinical:
    runtime: 120
    mem_mb: 10000 * attempt
  bcftools_filter_tnscope_clinical_tumor_only:
    runtime: 280
    mem_mb: 20000 * attempt
  bcftools_filter_tnscope_research_tumor_only:
    runtime: 280
    mem_mb: 20000 * attempt
  bcftools_filter_TNscope_umi_clinical_tumor_only:
    runtime: 280
    mem_mb: 5000 * attempt
  bcftools_filter_TNscope_umi_research_tumor_only:
    runtime: 280
    mem_mb: 5000 * attempt
  bcftools_filter_merged_clinical_tumor_only:
    runtime: 280
    mem_mb: 15000 * attempt
  bcftools_filter_merged_research_tumor_only:
    runtime: 280
    mem_mb: 15000 * attempt
  bcftools_filter_tnscope_clinical_tumor_normal:
    runtime: 280
    mem_mb: 10000 * attempt
  bcftools_filter_tnscope_research_tumor_normal:
    runtime: 280
    mem_mb: 10000 * attempt
  bcftools_filter_TNscope_umi_clinical_tumor_normal:
    runtime: 280
    mem_mb: 5000 * attempt
  bcftools_filter_TNscope_umi_research_tumor_normal:
    runtime: 280
    mem_mb: 5000 * attempt
  bcftools_filter_merged_clinical_tumor_normal:
    runtime: 280
    mem_mb: 10000 * attempt
  bcftools_filter_merged_research_tumor_normal:
    runtime: 280
    mem_mb: 10000 * attempt
  svdb_annotate_clinical_sv:
    runtime: 600
    mem_mb: 15000 * attempt
  svdb_annotate_somatic_research_sv:
    runtime: 720
    mem_mb: 25000 * attempt
  vep_somatic_research_sv:
    runtime: 720
  vcfanno_annotate_somaticSNV_clinical:
    runtime: 1080
    mem_mb: 10000 * attempt
  vep_annotate_somaticSNV_research:
    runtime: 1080
    mem_mb: 50000 * attempt
  bcftools_annotate_somaticINDEL_research:
    runtime: 60
    mem_mb: 4000 * attempt
  cadd_annotate_somaticINDEL_research:
    runtime: 1580
    mem_mb: 20000 * attempt
  bcftools_get_somaticINDEL_research:
    runtime: 60
    mem_mb: 5000 * attempt
  tmb_calculation:
    runtime: 280
    mem_mb: 5000 * attempt
  genmod_score_snvs:
    runtime: 280
    mem_mb: 5000 * attempt
  msisensorpro_msi_tumor_normal:
    runtime: 280
    mem_mb: 10000 * attempt
  msisensorpro_scan_reference:
    runtime: 280
    mem_mb: 1000 * attempt
  vep_annotate_germlineVAR_normal:
    runtime: 360
    mem_mb: 30000 * attempt
  vep_annotate_germlineVAR_tumor:
    runtime: 360
    mem_mb: 30000 * attempt
  sentieon_align_sort:
    runtime: 1440
    mem_mb: 15000 * attempt
  sentieon_realign:
    runtime: 1440
    mem_mb: 80000 * attempt
  sentieon_align_sort_umireads:
    runtime: 1440
    mem_mb: 15000 * attempt
  cap_base_quality:
    mem_mb: 10000 * attempt
    runtime: 300
  sentieon_dedup:
    runtime: 1440
    mem_mb: 80000 * attempt
  sentieon_dedup_consensus:
    runtime: 1440
  sentieon_base_calibration:
    mem_mb: 25000 * attempt
    runtime: 1440
  samtools_fixmate:
    mem_mb: 40000 * attempt
    runtime: 560
  bam_compress_tumor:
    mem_mb: 8000 * attempt
    runtime: 280
  bam_compress_normal:
    mem_mb: 8000 * attempt
    runtime: 280
  fastqc:
    mem_mb: 6000 * attempt
    runtime: 280
  fastp_quality_and_adapter_trim_wgs:
    mem_mb: 6000 * attempt
    runtime: 350
  fastp_adapter_trim_tga:
    mem_mb: 16000 * attempt
    runtime: 400
  fastp_quality_trim_tga:
    mem_mb: 16000 * attempt
    runtime: 350
  sentieon_umiextract_tga:
    mem_mb: 16000 * attempt
    runtime: 350
  samtools_merge_bamfiles:
    mem_mb: 70000 * attempt
    runtime: 800

set-threads:
  post_process_tnscope_info_fields_wgs: 1
  post_process_tnscope_info_fields_tga: 1
  tnscope_sort: 1
  merge_tnscope_to_mnvs: 4
  cnvpytor_tumor_only_wgs: 24
  igh_dux4_detection_tumor_only_wgs: 2
  igh_dux4_detection_tumor_normal_wgs: 2
  tiddit_sv_tumor_only_wgs: 24
  tiddit_sv_tumor_normal_wgs: 24
  ascat_tumor_normal_wgs: 24
  delly_cnv_tumor_only: 12
  delly_cnv_tumor_normal: 12
  delly_cnv_tumor_only_wgs: 24
  delly_cnv_tumor_normal_wgs: 24
  delly_sv_tumor_only_wgs: 24
  delly_sv_tumor_normal_wgs: 24
  manta_tumor_only_wgs: 24
  manta_tumor_normal_wgs: 24
  delly_sv_tumor_only_tga: 12
  delly_sv_tumor_normal_tga: 12
  manta_tumor_only_tga: 12
  manta_tumor_normal_tga: 12
  bcftools_quality_filter_svdb: 4
  svdb_merge_tumor_only: 8
  svdb_merge_tumor_normal: 8
  bcftools_process_SV_CNV: 4
  bcftools_sort_cnvkitCNV_research: 2
  cnvkit_call_CNV_research: 10
  purecn_call_CNV_research: 10
  bedtools_pad_bedfile: 1
  vardict_sort: 1
  gatk_update_vcf_sequence_dictionary: 5
  cnvkit_segment_CNV_research: 18
  bcftools_merge_germlineSNV_research: 2
  vardict_tumor_normal: 16
  sentieon_tnscope_tga_tumor_normal: 16
  post_process_vardict: 2
  vardict_tumor_only: 16
  sentieon_tnscope_tga_tumor_only: 16
  bcftools_quality_filter_TNscope_umi_tumor_only: 8
  bcftools_quality_filter_TNscope_umi_tumor_normal: 8
  bcftools_quality_filter_vardict_tumor_normal: 8
  bcftools_quality_filter_tnscope_tumor_normal_tga: 8
  bcftools_quality_filter_vardict_tumor_only: 8
  bcftools_quality_filter_tnscope_tumor_only_tga: 8
  bcftools_quality_filter_tnscope_tumor_normal_wgs: 8
  bcftools_quality_filter_tnscope_tumor_only_wgs: 8
  sentieon_tnscope_wgs_tumor_normal: 36
  sentieon_tnscope_wgs_tumor_only: 36
  merge_snv_vcfs: 2
  bcftools_normalise_vcfs: 2
  manta_germline_wgs: 36
  sentieon_DNAscope_wgs: 36
  manta_germline_tga: 16
  sentieon_DNAscope_tga: 12
  finalize_gens_outputfiles: 1
  gens_preprocess_tga: 1
  sentieon_DNAscope_gnomad_tga: 12
  gens_preprocess_wgs: 1
  gatk_denoise_read_counts: 10
  sentieon_DNAscope_gnomad: 36
  gatk_collectreadcounts: 5
  bedtools_sort_and_merge: 1
  extend_short_bedregions: 1
  create_coverage: 18
  create_target: 2
  sentieon_align_sort_umireads_umi: 12
  sentieon_tnscope_umi_tn: 12
  sentieon_tnscope_umi: 12
  bam_compress_normal_umi: 20
  bam_compress_tumor_umi: 20
  sentieon_consensusfilter_umi: 10
  sentieon_bwa_umiconsensus: 36
  sentieon_consensuscall_umi: 36
  samtools_view_calculatemeanfamilydepth_umi: 8
  picard_collecthsmetrics_umi: 8
  picard_umiaware: 12
  modify_tnscope_infofield_umi: 2
  bcftools_query_generatebackgroundaf_umitable: 8
  merge_cnv_pdf_reports: 1
  image_to_pdf: 1
  msi_to_pdf: 1
  txt_to_pdf: 1
  csv_to_pdf: 1
  somalier_relate: 1
  somalier_extract_tumor: 1
  somalier_extract_normal: 1
  sex_prediction_tga_tumor_only: 2
  sex_prediction_tga_tumor_normal: 2
  sex_prediction_wgs_tumor_only: 2
  sex_prediction_wgs_tumor_normal: 2
  sentieon_plot_qc_metrics_tga: 4
  sentieon_plot_qc_metrics_wgs: 4
  sentieon_qc_metrics_tga: 8
  sentieon_qc_metric_wgs: 8
  sentieon_wgs_metrics: 8
  picard_CollectWgsMetrics: 8
  samtools_qc_umi_collapsed: 16
  samtools_qc_tga: 16
  samtools_qc_wgs: 16
  sambamba_exon_depth: 8
  sambamba_panel_depth: 8
  cnv_report: 1
  collect_custom_qc_metrics: 1
  picard_CollectHsMetrics_WGS: 8
  picard_CollectAlignmentSummaryMetrics: 8
  picard_CollectHsMetrics: 8
  multiqc: 4
  mosdepth_coverage: 12
  gatk_create_readcount_pon: 86
  create_reference: 8
  dragen_align_call_tumor_only: 36
  concatenate_fastqs: 1
  vcfheader_rename_germline: 4
  vcf2cytosure_convert_tumor_normal: 8
  vcf2cytosure_convert_tumor_only: 8
  vcf2cytosure_convert: 8
  bcftools_filter_sv_research: 8
  bcftools_filter_sv_clinical: 8
  bcftools_filter_tnscope_clinical_tumor_only: 8
  bcftools_filter_tnscope_research_tumor_only: 8
  bcftools_filter_TNscope_umi_clinical_tumor_only: 4
  bcftools_filter_TNscope_umi_research_tumor_only: 4
  bcftools_filter_merged_clinical_tumor_only: 8
  bcftools_filter_merged_research_tumor_only: 8
  bcftools_filter_tnscope_clinical_tumor_normal: 8
  bcftools_filter_tnscope_research_tumor_normal: 8
  bcftools_filter_TNscope_umi_clinical_tumor_normal: 4
  bcftools_filter_TNscope_umi_research_tumor_normal: 4
  bcftools_filter_merged_clinical_tumor_normal: 8
  bcftools_filter_merged_research_tumor_normal: 8
  svdb_annotate_clinical_sv: 8
  svdb_annotate_somatic_research_sv: 36
  vep_somatic_research_sv: 36
  vcfanno_annotate_somaticSNV_clinical: 12
  vep_annotate_somaticSNV_research: 12
  bcftools_annotate_somaticINDEL_research: 4
  cadd_annotate_somaticINDEL_research: 4
  bcftools_get_somaticINDEL_research: 4
  tmb_calculation: 4
  genmod_score_snvs: 8
  msisensorpro_msi_tumor_normal: 24
  msisensorpro_scan_reference: 1
  vep_annotate_germlineVAR_normal: 10
  vep_annotate_germlineVAR_tumor: 10
  sentieon_align_sort: 12
  sentieon_realign: 36
  sentieon_align_sort_umireads: 12
  cap_base_quality: 10
  sentieon_dedup: 36
  sentieon_dedup_consensus: 36
  sentieon_base_calibration: 36
  samtools_fixmate: 16
  bam_compress_tumor: 20
  bam_compress_normal: 20
  fastqc: 4
  fastp_quality_and_adapter_trim_wgs: 12
  fastp_adapter_trim_tga: 4
  fastp_quality_trim_tga: 8
  sentieon_umiextract_tga: 8
  samtools_merge_bamfiles: 36
